version: '2'
services:
  event-service:
    image: yuryby/event_service:v1.0
    container_name: event-service
    environment:
      - JAVA_OPTS=-Xms1024MB -Xms1536MB 
    restart: always
    mem_limit: 2048MB 
    ports:
     - 8082:8087
    networks:
      - event-service

networks:
  event-service:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.61.0.0/16